<../../../mkconfig

# must match mem.h
BY2PG=4096

# Redefine target and architecture.
SYSTARG=$OSTARG
OBJTYPE=spim
INSTALLDIR=$ROOT/Inferno/$OBJTYPE/bin

loadaddr=0x81c00000
execaddr=0x81c0004c

# Re-read the target configuration file.
<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE

OBJ=\
	start0.$O\
	start1.$O\
	start2.$O\
	start3.$O

# Since each object file is assembled to produce its own binary, strip the
# suffix from each of them to find the binaries to delete when cleaning up.
CLEANEXTRA=${OBJ:%.$O=%} uImage-* *.bin main4 main5

default:V: $OBJ

main4:  start4.s main4.c
	$AS $ASFLAGS start4.s
	$CC $CFLAGS main4.c
	$LD -a -H0 -l -R$BY2PG -T$execaddr -s -o main4 start4.$O main4.$O
	mkimage -A mips -O linux -T kernel -C none -a $loadaddr -e $execaddr -n main4 -d main4 uImage-main4

%.$O:	%.s
	$AS $ASFLAGS $stem.s
	$LD -a -H0 -l -R$BY2PG -T$loadaddr -s -o $stem $stem.$O
	dd if=$stem of=$stem.bin bs=1 skip=76
	mkimage -A mips -O linux -T kernel -C none -a $loadaddr -e $loadaddr -n $stem -d $stem.bin uImage-$stem

%.$O:	%.c
	$CC $CFLAGS $stem.c

clean:V:	cleanconf-$SHELLTYPE
		rm -f *.[$OS] *.root.[sh] errstr.h *.out $CLEANEXTRA

cleanconf-sh:V:
		for i in $CONFLIST $CLEANCONFLIST
		do
			rm -f $i.c i$i i$i.* $i.ver
		done
