<../../mkconfig

TARG=\
	broke.dis\
	kill.dis\
	ls.dis\
	rm.dis\
	sh.dis\

MODULES=\

SYSMODULES=\
	sys.m\
	draw.m\
	env.m\
	filepat.m\
	bufio.m\
	readdir.m\
	workdir.m\

DISBIN=$ROOT/dis/tiny

<$ROOT/mkfiles/mkdis
