<../../mkconfig

CONF=apollo3.conf
CONFLIST=apollo3.conf
DATA2S=data2texts
loadaddr=0x10000
# Put data at the start of RAM.
dataaddr=0x10000000

SYSTARG=$OSTARG
OBJTYPE=thumb
INSTALLDIR=$ROOT/Inferno/$OBJTYPE/bin

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE

<| $SHELLNAME ../port/mkdevlist $CONF

# Create a directory to hold frozen modules and run the mkfrozen script to
# create them, defining MODFILES as a side effect.
<| $SHELLNAME ../cortexm/listfrozen $CONF

OBJ=\
	l.$O\
	main.$O\
	clock.$O\
	dump.$O\
	thumb2.$O\
	trap.$O\
	fpi.$O\
	fpimem.$O\
	fpithumb2.$O\
	devices/clocks.$O\
	devices/sys.$O\
#	$IP\
	$DEVS\
#	$ETHERS\
	$LINKS\
	$PORT\
	$MISC\
	$OTHERS\
	$CONF.root.$O\
	frozen.$O\

LIBNAMES=${LIBS:%=lib%.a}
LIBDIRS=$LIBS

# Strip off the devices prefix of any object paths.
NOPREFIXOBJ=${OBJ:devices/%=%} ${MODOBJ:frozen/%=%}

HFILES=\
	mem.h\
	dat.h\
	fns.h\
	../cortexm/fpi.h\
	../cortexm/thumb2.h\

ASFLAGS=$ASFLAGS -I../cortexm
CFLAGS=-wFV -I./include -I../cortexm -I$ROOT/include -I$ROOT/libinterp
LDFLAGS=-H0 -l -s -t -f -a
KERNDATE=`{$NDATE}

default:V: appl mkfreeze mkfrozendir frozen.h kernel

kernel: $OBJ $CONF.c $CONF.root.h $LIBNAMES
	$CC $CFLAGS -DKERNDATE=$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target -R0 -T$loadaddr -D$dataaddr $NOPREFIXOBJ $CONF.$O $LIBFILES

<../port/portmkfile

main.$O:	include/ureg.h

%.$O: ../cortexm/%.s
	$AS $ASFLAGS -I. -I../cortexm ../cortexm/$stem.s

%.$O: ../cortexm/%.c
	$CC $CFLAGS -I. -I../cortexm ../cortexm/$stem.c

mkfreeze:V:
	echo Making freeze
	(cd freeze; mk $MKFLAGS install)

mkfrozendir:V:
	echo Making frozen
	mkdir -p frozen

MODSRC=${MODOBJ:%.$O=%.s}

frozen.h:V: $MODSRC
	$SHELLNAME ../cortexm/mkfrozen $CONF
	# Only build frozen modules if they exist.
	$MODSRC || $AS $ASFLAGS $MODSRC

frozen/%.s:
	echo $target

%.fdis:Q:
	# $target is built by the frozen.c rule that builds frozen.h

appl:V:
	limbo -o $ROOT/dis/tiny/ls.dis $ROOT/appl/tiny/ls.b
#	limbo -o $ROOT/dis/makecol.dis appl/makecol.b
#	limbo -o $ROOT/dis/banner.dis appl/banner.b
#	limbo -o $ROOT/dis/banner16.dis appl/banner16.b
	limbo -o $ROOT/dis/blink.dis appl/blink.b
	limbo -o $ROOT/dis/ink.dis appl/ink.b
	limbo -o $ROOT/dis/aht.dis appl/aht.b
	limbo -o $ROOT/dis/makecol.dis appl/makecol.b
	limbo -o $ROOT/dis/mandel.dis appl/mandel.b
	limbo -o $ROOT/dis/ledsegment.dis appl/ledsegment.b
	limbo -o $ROOT/dis/floattest.dis appl/floattest.b
	limbo -o $ROOT/dis/textmandel.dis appl/textmandel.b
